# Generated by Django 6.0.4 on 2026-04-23 12:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('phone_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('phone_title', models.CharField(max_length=50, unique=True)),
                ('phone_brand', models.CharField(max_length=100)),
                ('phone_model', models.CharField(max_length=50)),
                ('phone_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
