# Generated by Django 6.0.4 on 2026-04-23 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='created_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
